# **Import the needed Modules and Libraries**

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait # report 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import time

# **Download and Use the correct ChromeDriver**

In [2]:
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
driver.get("https://www.google.com")
serch_box = driver.find_element(By.XPATH, "//textarea[@id='APjFqb']")

In [ ]:
#Get Noon website first page
driver.get("https://www.noon.com/egypt-ar/electronics-and-mobiles/mobiles-and-accessories/mobiles-20905/?page=1")

In [ ]:
# Get the full HTML of the first product card to know the structer of the data and how to extract it 
cards = driver.find_elements(By.CSS_SELECTOR, "div[class*='layoutWrapper'] > div")
print(cards[0].get_attribute("innerHTML"))

<a class="PBoxLinkHandler-module-scss-module__WvRpgq__productBoxLink" href="/egypt-ar/smart-10-dual-sim-iris-blue-3-3gb-ram-64gb-4g-middle-east-version/N70182485V/p/?o=dd48f512f7640a9d"><div class="ProductBoxVertical-module-scss-module__NG8XsG__wrapper"><div data-qa="productImagePLP_سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية" class="ProductImageSection-module-scss-module__8NuU7G__imageSection"><div class="ProductImageCarousel-module-scss-module__SlkSTG__wrapper" style="--transition-duration:1000ms"><div class="ProductImageCarousel-module-scss-module__SlkSTG__slidesWrapper"><div class="ProductImageCarousel-module-scss-module__SlkSTG__slide"><div class="ProductImage-module-scss-module__DS-hBG__imageContainer"><div class="ProductImage-module-scss-module__DS-hBG__imageWrapper"><img class="ProductImageCarousel-module-scss-module__SlkSTG__productImage" width="auto" height="100%" src="https://f.nooncdn.com/p/pnsku/N70182485V/45/_/1764242115/8defba4c-6395-4a25-b57d-25f546158fd8.jpg?width=800" alt="إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية - Image 1" loading="lazy" style="margin:0 auto;width:auto;height:100%"></div></div></div><div class="ProductImageCarousel-module-scss-module__SlkSTG__slide"><div class="ProductImage-module-scss-module__DS-hBG__imageContainer"><div class="ProductImage-module-scss-module__DS-hBG__imageWrapper"><img class="" width="auto" height="100%" src="https://f.nooncdn.com/p/pnsku/N70182485V/45/_/1764242123/da44f28a-80bd-4b21-9cbc-26370fa63dba.jpg?width=800" alt="إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية - Image 2" loading="lazy" style="margin:0 auto;width:auto;height:100%"></div></div></div><div class="ProductImageCarousel-module-scss-module__SlkSTG__slide"><div class="ProductImage-module-scss-module__DS-hBG__imageContainer"><div class="ProductImage-module-scss-module__DS-hBG__imageWrapper"><img class="" width="auto" height="100%" src="https://f.nooncdn.com/p/pnsku/N70182485V/45/_/1764242058/026ba0eb-af7c-4025-9368-39288dc44eb2.jpg?width=800" alt="إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية - Image 3" loading="lazy" style="margin:0 auto;width:auto;height:100%"></div></div></div><div class="ProductImageCarousel-module-scss-module__SlkSTG__slide"><div class="ProductImage-module-scss-module__DS-hBG__imageContainer"><div class="ProductImage-module-scss-module__DS-hBG__imageWrapper"><img class="" width="auto" height="100%" src="https://f.nooncdn.com/p/pnsku/N70182485V/45/_/1764242112/0d7e5d7c-779a-42f6-bee2-b8682e999b33.jpg?width=800" alt="إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية - Image 4" loading="lazy" style="margin:0 auto;width:auto;height:100%"></div></div></div><div class="ProductImageCarousel-module-scss-module__SlkSTG__slide"><div class="ProductImage-module-scss-module__DS-hBG__imageContainer"><div class="ProductImage-module-scss-module__DS-hBG__imageWrapper"><img class="" width="auto" height="100%" src="https://f.nooncdn.com/p/pnsku/N70182485V/45/_/1764242114/65c00807-7ff4-4a2e-b05c-ada477b2e1e8.jpg?width=800" alt="إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية - Image 5" loading="lazy" style="margin:0 auto;width:auto;height:100%"></div></div></div></div><div class="ProductImageCarousel-module-scss-module__SlkSTG__paginationWrapper" style="width:58px"><button class="ProductImageCarousel-module-scss-module__SlkSTG__paginationBullet ProductImageCarousel-module-scss-module__SlkSTG__active" style="width:6px;height:6px"></button><button class="ProductImageCarousel-module-scss-module__SlkSTG__paginationBullet" style="width:5px;height:5px"></button><button class="ProductImageCarousel-module-scss-module__SlkSTG__paginationBullet" style="width:4px;height:4px"></button><button class="ProductImageCarousel-module-scss-module__SlkSTG__paginationBullet" style="width:3px;height:3px"></button><button class="ProductImageCarousel-module-scss-module__SlkSTG__paginationBullet" style="width:2px;height:2px"></button></div><div><button class="ProductImageCarouselButtons-module-scss-module__1XfBmW__arrow ProductImageCarouselButtons-module-scss-module__1XfBmW__prev" type="button" aria-label="prev carousel navigation"><img src="https://f.nooncdn.com/s/app/com/noon/icons/left-chevron-white.svg" alt="prev carousel navigation" width="24" height="24" style="width:24px;height:24px" loading="eager"></button><button class="ProductImageCarouselButtons-module-scss-module__1XfBmW__arrow ProductImageCarouselButtons-module-scss-module__1XfBmW__next" type="button" aria-label="next carousel navigation"><img src="https://f.nooncdn.com/s/app/com/noon/icons/right-chevron-white.svg" alt="next carousel navigation" width="24" height="24" style="width:24px;height:24px" loading="eager"></button></div></div><div class="ProductImageOverlay-module-scss-module__G8Es1W__overlayWrapper"><div class="ProductImageOverlay-module-scss-module__G8Es1W__overlayHeader"><div class="ProductImageTags-module-scss-module__ZPidPa__tagsWrapper"><div class="ProductImageTags-module-scss-module__ZPidPa__tagCover"></div></div><div class="ProductImageOverlay-module-scss-module__G8Es1W__wishlistButton"><button type="button" class="AddToWishlist-module-scss-module__58M9wG__wishlistButton"><span class="AddToWishlist-module-scss-module__58M9wG__wishlistButtonInner"><img src="https://f.nooncdn.com/s/app/com/noon/icons/wishlistV2.svg" alt="wishlist" width="24" height="24" style="width:24px;height:24px" loading="eager"></span></button></div></div><div class="ProductImageOverlay-module-scss-module__G8Es1W__overlayFooter"><div class="ProductImageOverlay-module-scss-module__G8Es1W__actionsRow"><div class="QuickAtc-module-scss-module__x7ROma__container" style="--width-desktop:36px;--width-mobile:32px;--height-desktop:36px;--height-mobile:32px;--spacing-desktop:6px;--spacing-mobile:4px;--qty-icon-font-size-desktop:12px;--qty-icon-font-size-mobile:10px"><div class="QuickAtc-module-scss-module__x7ROma__atcContainer"><button class="QuickAtc-module-scss-module__x7ROma__atcCta"><img src="https://f.nooncdn.com/s/app/com/noon/icons/quick-atc-add-to-cart-v2-black.svg" alt="add-to-cart" width="24" height="24" style="width:24px;height:24px" loading="eager"></button></div></div></div></div></div></div><div class="ProductDetailsSection-module-scss-module__Y6u1Qq__wrapper"><h2 class="ProductDetailsSection-module-scss-module__Y6u1Qq__title" data-qa="plp-product-box-name" title="إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية">إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت + 64 جيجابايت أيريس أزرق - النسخة الشرق أوسطية</h2><div class="RatingPreviewStar-module-scss-module__zCpaOG__mainContainer RatingPreviewStar-module-scss-module__zCpaOG__isRenderedOnNewProductBox"><div class="RatingPreviewStar-module-scss-module__zCpaOG__container"><div class="RatingPreviewStar-module-scss-module__zCpaOG__starContainer"><svg width="14" height="14" viewBox="0 0 12 10" fill="#82AE04" xmlns="http://www.w3.org/2000/svg"><path d="M6.25333 8.28568C6.09679 8.19352 5.90258 8.19352 5.74604 8.28568L3.31597 9.71618C2.93433 9.94084 2.47058 9.59509 2.57696 9.16519L3.22394 6.55064C3.27013 6.36399 3.20519 6.16739 3.05692 6.04497L0.955287 4.30981C0.608396 4.02341 0.786618 3.46036 1.23513 3.42573L4.03001 3.20991C4.21511 3.19561 4.37705 3.07994 4.4506 2.90948L5.5406 0.383314C5.71429 -0.0192352 6.28508 -0.019235 6.45877 0.383315L7.54877 2.90948C7.62232 3.07994 7.78426 3.19561 7.96936 3.2099L10.7647 3.42573C11.2132 3.46036 11.3914 4.02346 11.0445 4.30984L8.9425 6.04497C8.7942 6.16739 8.72924 6.36401 8.77543 6.55068L9.42241 9.16519C9.52879 9.59508 9.06504 9.94084 8.6834 9.71618L6.25333 8.28568Z"></path></svg></div><div class="RatingPreviewStar-module-scss-module__zCpaOG__textCtr">4.4</div><div class="RatingPreviewStar-module-scss-module__zCpaOG__countCtr"><svg width="3" height="14" viewBox="0 0 3 10" fill="none" xmlns="http://www.w3.org/2000/svg" style="transform:scaleX(-1)"><path d="M2.17635 9.26182C1.46726 7.88727 1.0309 6.63273 1.0309 4.82182C1.0309 3 1.46726 1.75636 2.17635 0.370909L1.67453 0C0.692716 1.35273 0.136353 3.06545 0.136353 4.82182C0.136353 6.57818 0.692716 8.29091 1.67453 9.64364L2.17635 9.26182Z" fill="currentColor"></path></svg><span>724</span><svg width="3" height="14" viewBox="0 0 3 10" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2.17635 9.26182C1.46726 7.88727 1.0309 6.63273 1.0309 4.82182C1.0309 3 1.46726 1.75636 2.17635 0.370909L1.67453 0C0.692716 1.35273 0.136353 3.06545 0.136353 4.82182C0.136353 6.57818 0.692716 8.29091 1.67453 9.64364L2.17635 9.26182Z" fill="currentColor"></path></svg></div></div></div><div class="ProductDetailsSection-module-scss-module__Y6u1Qq__priceNudgesCtr"><div data-qa="plp-product-box-price" class="Price-module-scss-module__q-4KEG__container Price-module-scss-module__q-4KEG__pBox"><div class="Price-module-scss-module__q-4KEG__sellingPrice Price-module-scss-module__q-4KEG__isRenderedOnNewProductBox"><span class="Price-module-scss-module__q-4KEG__currency">جنيه</span><strong class="Price-module-scss-module__q-4KEG__amount">5,099</strong></div></div><div class="Nudges-module-scss-module__dNOKTG__nudgesContainer" style="--animation-duration:5.2s;--nudge-height:16px;--animation-name:nudgeAnimationKeyframe-dd48f512f7640a9d-2"><div class="Nudges-module-scss-module__dNOKTG__nudgesWrapper"><div class="Nudges-module-scss-module__dNOKTG__nudge"><img alt="nudge icon" class="Nudges-module-scss-module__dNOKTG__nudgeIcon" src="https://f.nooncdn.com/mpcms/EN0001/assets/77701d64-1162-4836-93f9-584b39add4fd.png"><div class="Nudges-module-scss-module__dNOKTG__nudgeText">توصيل مجاني</div></div><div class="Nudges-module-scss-module__dNOKTG__nudge"><img alt="nudge icon" class="Nudges-module-scss-module__dNOKTG__nudgeIcon" src="https://f.nooncdn.com/mpcms/EN0001/assets/d2809d6f-556e-414a-b0f9-51cef68684bc.png"><div class="Nudges-module-scss-module__dNOKTG__nudgeText">بتخلّص بسرعة</div></div><div class="Nudges-module-scss-module__dNOKTG__nudge"><img alt="nudge icon" class="Nudges-module-scss-module__dNOKTG__nudgeIcon" src="https://f.nooncdn.com/mpcms/EN0001/assets/77701d64-1162-4836-93f9-584b39add4fd.png"><div class="Nudges-module-scss-module__dNOKTG__nudgeText">توصيل مجاني</div></div></div><style>
        @keyframes nudgeAnimationKeyframe-dd48f512f7640a9d-2 {
            0%{transform:translateY(0px);}25%{transform:translateY(0px);}50%{transform:translateY(-16px);}75%{transform:translateY(-16px);}100%{transform:translateY(-32px);}
        }
    </style></div></div><div class="ProductDetailsSection-module-scss-module__Y6u1Qq__additionalInfo"><div data-qa="product-noon-express" class="ProductDetailsSection-module-scss-module__Y6u1Qq__supportDetailsRow"><div class="ProductDetailsSection-module-scss-module__Y6u1Qq__fbnCtr"><div class="FulfilmentBadge-module-scss-module___6v63G__container FulfilmentBadge-module-scss-module___6v63G__small"><img src="https://f.nooncdn.com/s/app/com/noon/images/fulfilment_express_v2-ar.svg" alt="noon-express" width="auto" height="100%" style="width:auto;height:100%" loading="eager"></div><div class="ProductDetailsSection-module-scss-module__Y6u1Qq__deliveryDate ProductDetailsSection-module-scss-module__Y6u1Qq__estimatedDeliveryDateNewTextStyles">احصل عليه خلال <b>7 ابريل</b></div></div></div></div></div></div><div class="PBoxLinkHandler-module-scss-module__WvRpgq__loaderCtr"><div class="Loader-module-scss-module__1m0mca__spinnerLoader" style="--loader-size:50px;--border-width:5px;--loader-color:#3866df"></div></div></a>

# **Start Scraping and Exctrating the needed data**
(Product_Name, Product_Price, Product_Rating, Produt_Reviews, Product_Photo_URL)

In [8]:
get_names = []
get_prices = []
get_ratings =[]
get_reviews =[]
get_photo_URLs =[]

for page in range(1,19):
    print(f"Scraping page {page}/18")
    url = f"https://www.noon.com/egypt-ar/electronics-and-mobiles/mobiles-and-accessories/mobiles-20905/?page={page}"
    driver.get(url)
    time.sleep(4)

    #Get product_name
    name_elements = driver.find_elements(
        By.CSS_SELECTOR,
        "div.ProductDetailsSection-module-scss-module__Y6u1Qq__wrapper > h2")
    names =[]
    for element in name_elements:
        names.append(element.text.strip())
    
    #Get product_price
    price_elements = driver.find_elements(
        By.CSS_SELECTOR,
        "strong.Price-module-scss-module__q-4KEG__amount"
    )
    price = []
    for element in price_elements:
        price.append(element.text.strip())
    
    #Get product_rating
    rating_elements = driver.find_elements(
        By.CSS_SELECTOR,
        "div.RatingPreviewStar-module-scss-module__zCpaOG__textCtr"
    )
    rating = []
    for element in rating_elements:
        rating.append(element.text.strip())

    #Get product_reviews
    review_elements = driver.find_elements(
        By.CSS_SELECTOR,
        "div.RatingPreviewStar-module-scss-module__zCpaOG__countCtr span"
    )
    reviews = []
    for el in review_elements:
        reviews.append(el.text.strip())

    #Get Photos_Url
    photo_elements = driver.find_elements(
        By.CSS_SELECTOR,
        "img.ProductImageCarousel-module-scss-module__SlkSTG__productImage"
    )
    photos = []
    for el in photo_elements:
        photos.append(el.get_attribute("src"))
    

    #alignment all the product features to name len to create df
    # ── Align all lists to names length ────────────────────────
    n = len(names)

    while len(price) < n:
        price.append("N/A")
    price = price[:n]

    while len(rating) < n:
        rating.append("N/A")
    rating = rating[:n]

    while len(reviews) < n:
        reviews.append("N/A")
    reviews = reviews[:n]

    while len(photos) < n:
        photos.append("N/A")
    photos = photos[:n]

    #append in master lst
    for name in names:
        get_names.append(name)

    for price in price:
        get_prices.append(price)

    for rating in rating:
        get_ratings.append(rating)

    for review in reviews:
        get_reviews.append(review)

    for photo in photos:
        get_photo_URLs.append(photo)

    print(f"  Page {page} done: {n} products found | Total so far: {len(get_names)}")
    time.sleep(2)

print(f"\n Total products scraped: {len(get_names)}")

Scraping page 1/18
  Page 1 done: 50 products found | Total so far: 50
Scraping page 2/18
  Page 2 done: 50 products found | Total so far: 100
Scraping page 3/18
  Page 3 done: 50 products found | Total so far: 150
Scraping page 4/18
  Page 4 done: 50 products found | Total so far: 200
Scraping page 5/18
  Page 5 done: 50 products found | Total so far: 250
Scraping page 6/18
  Page 6 done: 48 products found | Total so far: 298
Scraping page 7/18
  Page 7 done: 50 products found | Total so far: 348
Scraping page 8/18
  Page 8 done: 50 products found | Total so far: 398
Scraping page 9/18
  Page 9 done: 49 products found | Total so far: 447
Scraping page 10/18
  Page 10 done: 49 products found | Total so far: 496
Scraping page 11/18
  Page 11 done: 49 products found | Total so far: 545
Scraping page 12/18
  Page 12 done: 50 products found | Total so far: 595
Scraping page 13/18
  Page 13 done: 50 products found | Total so far: 645
Scraping page 14/18
  Page 14 done: 50 products found | Total so far: 695
Scraping page 15/18
  Page 15 done: 50 products found | Total so far: 745
Scraping page 16/18
  Page 16 done: 50 products found | Total so far: 795
Scraping page 17/18
  Page 17 done: 50 products found | Total so far: 845
Scraping page 18/18
  Page 18 done: 32 products found | Total so far: 877

 Total products scraped: 877

In [12]:
#Store extracted data in dataframe
data = pd.DataFrame({
    "Product Name": get_names,
    "Price": get_prices,
    "Rating": get_ratings,
    "Reviews": get_reviews,
    "Photo URL": get_photo_URLs
})

data.head(10)

,Product Name,Price,Rating,Reviews,Photo URL
0,إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت +...,"5,099",4.4,724,https://f.nooncdn.com/p/pnsku/N70182485V/45/_/...
1,سامسونج جالاكسي A17 ثنائي الشريحة 4G أسود 6GB ...,"9,999",4.5,1.2K,https://f.nooncdn.com/p/pzsku/Z31ECA424BE18ABD...
2,إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت +...,"5,199",4.4,724,https://f.nooncdn.com/p/pnsku/N70182486V/45/_/...
3,سامسونج جالاكسي A17 ثنائي الشريحة 4G أسود 8GB ...,"11,999",4.5,1.2K,https://f.nooncdn.com/p/pzsku/ZC23004F18866BE5...
4,سامسونج جالاكسي A07 ثنائي الشريحة أسود 4GB 128...,"7,240",4.5,2.0K,https://f.nooncdn.com/p/pzsku/Z549671868916F4F...
5,إنفينيكس هوت 60 برو ثنائي الشريحة أنيق أسود 8+...,"9,700",4.6,166,https://f.nooncdn.com/p/pnsku/N70204530V/45/_/...
6,إيتيل A90 ثنائي الشريحة أسود متلألئ 3+5 جيجابا...,"4,149",4.2,2.2K,https://f.nooncdn.com/p/pnsku/N70169194V/45/_/...
7,إنفينيكس سمارت 10 ثنائي الشريحة 4+4 جيجابايت +...,"6,342",4.4,1.3K,https://f.nooncdn.com/p/pnsku/N70182484V/45/_/...
8,فيفو V50 لايت AI 5G ثنائي الشريحة ذهب تيتانيوم...,"14,999",4.3,1.3K,https://f.nooncdn.com/p/pnsku/N70166558V/45/_/...
9,سامسونج جالاكسي A07 ثنائي الشريحة لون بنفسجي ف...,"9,845",5.0,9,https://f.nooncdn.com/p/pzsku/ZBD74DD5FAFD27D6...

In [ ]:
#Data Cleaning 
data = data.drop_duplicates(subset="Product Name")
data["Price"] = data["Price"].apply(lambda x: float(x.replace(",", "")) if x != "N/A" else None)
data = data.reset_index(drop=True)

print(f"Final dataset: {data.shape[0]} products, {data.shape[1]} columns")
data.head(10)

Final dataset: 860 products, 5 columns

,Product Name,Price,Rating,Reviews,Photo URL
0,إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت +...,5099.0,4.4,724,https://f.nooncdn.com/p/pnsku/N70182485V/45/_/...
1,سامسونج جالاكسي A17 ثنائي الشريحة 4G أسود 6GB ...,9999.0,4.5,1.2K,https://f.nooncdn.com/p/pzsku/Z31ECA424BE18ABD...
2,إنفينيكس سمارت 10 ثنائي الشريحة 3+3 جيجابايت +...,5199.0,4.4,724,https://f.nooncdn.com/p/pnsku/N70182486V/45/_/...
3,سامسونج جالاكسي A17 ثنائي الشريحة 4G أسود 8GB ...,11999.0,4.5,1.2K,https://f.nooncdn.com/p/pzsku/ZC23004F18866BE5...
4,سامسونج جالاكسي A07 ثنائي الشريحة أسود 4GB 128...,7240.0,4.5,2.0K,https://f.nooncdn.com/p/pzsku/Z549671868916F4F...
5,إنفينيكس هوت 60 برو ثنائي الشريحة أنيق أسود 8+...,9700.0,4.6,166,https://f.nooncdn.com/p/pnsku/N70204530V/45/_/...
6,إيتيل A90 ثنائي الشريحة أسود متلألئ 3+5 جيجابا...,4149.0,4.2,2.2K,https://f.nooncdn.com/p/pnsku/N70169194V/45/_/...
7,إنفينيكس سمارت 10 ثنائي الشريحة 4+4 جيجابايت +...,6342.0,4.4,1.3K,https://f.nooncdn.com/p/pnsku/N70182484V/45/_/...
8,فيفو V50 لايت AI 5G ثنائي الشريحة ذهب تيتانيوم...,14999.0,4.3,1.3K,https://f.nooncdn.com/p/pnsku/N70166558V/45/_/...
9,سامسونج جالاكسي A07 ثنائي الشريحة لون بنفسجي ف...,9845.0,5.0,9,https://f.nooncdn.com/p/pzsku/ZBD74DD5FAFD27D6...

In [15]:
data.isnull().sum()

Product Name    0
Price           0
Rating          0
Reviews         0
Photo URL       0
dtype: int64

In [16]:
data.to_csv("noon_products.csv", index=False)